version: "3.8"

services:
  auth_service:
    build: ./services/auth_service
    container_name: auth_service
    ports:
      - "8001:8000"
    env_file:
      - .env
      - ./services/auth_service/.env
    depends_on:
      - db_auth
      - redis

  admin_service:
    build: ./services/admin_service
    container_name: admin_service
    ports:
      - "8002:8000"
    env_file:
      - .env
      - ./services/admin_service/.env
    depends_on:
      - db_admin

  email_worker:
    build: ./services/email_service
    container_name: email_worker
    env_file:
      - .env
      - ./services/email_service/.env
    depends_on:
      - redis

  gateway:
    image: nginx:latest
    container_name: gateway
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth_service
      - admin_service

  db_auth:
    image: postgres:15
    container_name: db_auth
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB_AUTH_SERVICE}
      POSTGRES_USER: ${POSTGRES_USER_AUTH_SERVICE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_AUTH_SERVICE}
    ports:
      - "${POSTGRES_PORT_AUTH_SERVICE}:5432"

  db_admin:
    image: postgres:15
    container_name: db_admin
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB_ADMIN_SERVICE}
      POSTGRES_USER: ${POSTGRES_USER_ADMIN_SERVICE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_ADMIN_SERVICE}
    ports:
      - "${POSTGRES_PORT_ADMIN_SERVICE}:5432"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  postgres_data:
