

services:
  # 🔐 Сервис авторизации
  auth_service:
    build: ./services/auth_service
    container_name: auth_service
    ports:
      - "8001:8000"
    restart: always

#  # 🎬 Сервис контента (каталог фильмов)
#  content_service:
#    build: ./services/content_service
#    container_name: content_service
#    ports:
#      - "8002:8000"
#    restart: always

#  # 📦 Сервис заказов
#  order_service:
#    build: ./services/order_service
#    container_name: order_service
#    ports:
#      - "8003:8000"
#    restart: always
#
#  # 💳 Платёжный сервис
#  payment_service:
#    build: ./services/payment_service
#    container_name: payment_service
#    ports:
#      - "8004:8000"
#    restart: always
#
#  # 🛠️ Админка/модерация
#  admin_service:
#    build: ./services/admin_service
#    container_name: admin_service
#    ports:
#      - "8005:8000"
#    restart: always

  # 🌐 Nginx как gateway
  gateway:
    image: nginx:alpine
    container_name: gateway
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - auth_service
#      - content_service
#      - order_service
#      - payment_service
#      - admin_service

