version: '3.9'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
      - ./frontend/dist:/output
    command: sh -c "npm install && npm run build && cp -r dist/* /output"

  nginx:
    image: nginx:alpine
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
