events {}

http {
    upstream auth_service {
        server auth_service:8000;
    }

    upstream admin_service {
        server admin_service:8000;
    }

    upstream content_service {
        server content_service:8000;
    }

    server {
        listen 80;

        location /auth/ {
            proxy_pass http://auth_service/;
            proxy_set_header Host $host;
        }

        location /admin/ {
            proxy_pass http://admin_service/;
            proxy_set_header Host $host;
        }

        location /content/ {
            proxy_pass http://content_service/;
            proxy_set_header Host $host;
        }
    }
}
